version: '3.7'
services:

  mongo-staging-db:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'

  docrender-staging-etl:
    container_name: 'docrender'
    build:
      context: ./docrender/
      dockerfile: Dockerfile
    ports:
      - '10070:10070'
    depends_on:
      - 'mongo-staging-db'

  api-dos:
    container_name: 'api'
    build: './soa'
    ports:
      - '8080:8080'

  ui-dos:
    container_name: ui
    build:
      context: ./ui/
      dockerfile: Dockerfile
    ports:
     - '3000:80'
