version: '3.7'
services:

  mysql_staging_db:
    image: 'mariadb:10.3.22-bionic'
    container_name: 'mysql'
    ports:
      - '3306:3306'

  mongo_staging_db:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'

  docrender_staging_etl:
    container_name: 'docrender'
    build: './docrender'
    ports:
      - '10070:10070'
    depends_on:
      - 'mongo_staging_db'

  api_dos:
    container_name: 'api'
    build: './soa'
    ports:
      - '8080:8080'

  ui_dos:
    container_name: 'ui'
    build: './ui'
    ports:
     - '3000:80'

  pg_dos:
    image: 'postgres:12-alpine'
    container_name: 'pgsql'
    ports:
      - '5432:5432'
